# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Upload to Firebase App Distribution"
  lane :deploy_firebase do |options|
    firebase_app_distribution(
        app: options[:app_id],
        groups: options[:groups],
        release_notes_file: options[:release_notes_file],
        service_credentials_file: options[:account_json],
        apk_path: options[:apk_path]
    )
  end

  desc "Upload to Huawei AppGallery"
  lane :deploy_appgallery do |options|
    huawei_appgallery_connect(
        app_id: options[:app_id],
        client_id: options[:client_id],
        client_secret: options[:client_secret],
        changelog_path: options[:changelog_path],
        apk_path: options[:apk_path],
        submit_for_review: false,
    )
  end

  desc "Upload to Google Play"
  lane :deploy_google_play do |options|
    upload_to_play_store(
        apk: options[:apk_path],
        track: "beta",
        json_key: options[:account_json]
    )
  end
end
